import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import cv2
from skimage.feature import graycomatrix, graycoprops

# VAE model
class VAE(nn.Module):
    def __init__(self, latent_dim=128):
        super(VAE, self).__init__()
        # encoder part
        self.encoder = nn.Sequential(
            nn.Conv2d(3, 32, 4, 2, 1), 
            nn.BatchNorm2d(32), 
            nn.LeakyReLU(0.1),
            nn.Conv2d(32, 64, 4, 2, 1), 
            nn.BatchNorm2d(64), 
            nn.LeakyReLU(0.1),
            nn.Conv2d(64, 128, 4, 2, 1), 
            nn.BatchNorm2d(128), 
            nn.LeakyReLU(0.1),
            nn.Flatten()
        )
        # latent space, we need to output both mean and the variance for the reparameterization trick
        self.fc_mu = nn.Linear(128 * 8 * 8, latent_dim)
        self.fc_var = nn.Linear(128 * 8 * 8, latent_dim)
        
        # decoder part
        self.decoder_input = nn.Linear(latent_dim, 128 * 8 * 8)
        self.decoder = nn.Sequential(
            nn.ConvTranspose2d(128, 64, 4, 2, 1), 
            nn.BatchNorm2d(64), 
            nn.ReLU(),
            nn.ConvTranspose2d(64, 32, 4, 2, 1), 
            nn.BatchNorm2d(32), 
            nn.ReLU(),
            nn.ConvTranspose2d(32, 3, 4, 2, 1), 
            nn.Tanh() # we need the output to be in the range of [-1, 1] to match the input image normalization
        )

    # here is the reparameterization trick: z = mu + eps * std
    def reparameterize(self, mu, log_var):
        std = torch.exp(0.5 * log_var)
        eps = torch.randn_like(std)
        return mu + eps * std

    def forward(self, x):
        x = self.encoder(x)
        mu, log_var = self.fc_mu(x), torch.log(self.fc_var(x)) # here is the log of the variance
        z = self.reparameterize(mu, log_var)
        z = self.decoder_input(z).view(-1, 128, 8, 8)
        return self.decoder(z), mu, log_var

# GAN model, which contains both generator and discriminator\
# here, the generator's job is to take a random noise vector and generate a fake image
class Generator(nn.Module):
    def __init__(self, latent_dim=100):
        super().__init__()
        self.main = nn.Sequential(
            nn.ConvTranspose2d(latent_dim, 512, 4, 1, 0), 
            nn.BatchNorm2d(512), 
            nn.ReLU(),
            nn.ConvTranspose2d(512, 256, 4, 2, 1), 
            nn.BatchNorm2d(256), 
            nn.ReLU(),
            nn.ConvTranspose2d(256, 128, 4, 2, 1), 
            nn.BatchNorm2d(128), 
            nn.ReLU(),
            nn.ConvTranspose2d(128, 64, 4, 2, 1), 
            nn.BatchNorm2d(64), 
            nn.ReLU(),
            nn.ConvTranspose2d(64, 3, 4, 2, 1), 
            nn.Tanh()
        )


    def forward(self, x): 
        return self.main(x)

# the discriminator's job is to take an image and output a probability of it being real or fake, of course, the input image also can be generated by the generator
class Discriminator(nn.Module):
    def __init__(self):
        super().__init__()
        self.main = nn.Sequential(
            nn.Conv2d(3, 64, 4, 2, 1), 
            nn.LeakyReLU(0.1),
            nn.Conv2d(64, 128, 4, 2, 1), 
            nn.BatchNorm2d(128), 
            nn.LeakyReLU(0.1),
            nn.Conv2d(128, 256, 4, 2, 1), 
            nn.BatchNorm2d(256), 
            nn.LeakyReLU(0.1),
            nn.Conv2d(256, 512, 4, 2, 1), 
            nn.BatchNorm2d(512), 
            nn.LeakyReLU(0.1),
            nn.Conv2d(512, 1, 4, 1, 0), 
            nn.Sigmoid()
        )
    def forward(self, x): 
        return self.main(x).view(-1, 1)

# diffusion model, with the simple unet
class Diffusion(nn.Module):
    def __init__(self):
        super().__init__()
        # here is the time embedding part, we use a simple full connected network to encode the time step t into a vector, then this vector will be added to the feature data 
        self.time_emb = nn.Sequential(
            nn.Linear(1, 64), 
            nn.ReLU(), 
            nn.Linear(64, 64)
        )
        
        # downsampling
        self.input_layer = nn.Conv2d(3, 64, 3, padding=1)
        self.down = nn.Conv2d(64, 128, 4, stride=2, padding=1) # 32x32
        
        # upsampling
        self.up = nn.ConvTranspose2d(128, 64, 4, stride=2, padding=1) # 64x64
        self.output_layer = nn.Conv2d(64, 3, 3, padding=1)

    def forward(self, x, t):
        # first do the time embedding
        t_emb = self.time_emb(t.view(-1, 1).float()).view(-1, 64, 1, 1)
        h = self.input_layer(x) + t_emb # combine the time information with the input image features
        h = F.relu(h)
        h = self.down(h)
        h = F.relu(h)
        h = self.up(h)
        h = F.relu(h)
        return self.output_layer(h) # predict the noise distribution

# here are the metrics
def metrics(img_tensor):
    # first we need to convert the tensor back to a numpy array, and also in a grey scale, because in hw04 1.1 said "grayscale image", so we need to deal with the color image and convert it to grayscale

    # here we use the opencv library and the skimage library
    img = img_tensor.detach().cpu().permute(1, 2, 0).numpy()
    img = ((img + 1) * 127.5).clip(0, 255).astype(np.uint8)
    gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
    
    m = {}
    
    # here we compute the laplacian variance
    m['VOL'] = cv2.Laplacian(gray, cv2.CV_64F).var()
    
    # here we compute the tenengrad criterion, which is treated as the first-order analogue of the laplacian variance
    gx = cv2.Sobel(gray, cv2.CV_64F, 1, 0, ksize=3)
    gy = cv2.Sobel(gray, cv2.CV_64F, 0, 1, ksize=3)
    m['TEN'] = np.var(np.sqrt(gx**2 + gy**2))
    
    # here we compute the High-frequency energy ratio
    # first we need to do a 2D fourier transform to get the frequency domain representation of the image
    f = np.fft.fft2(gray)
    fshift = np.fft.fftshift(f)
    fshift_abs = np.abs(fshift)
    # here is the h and w shoun in the hw04 width and height
    h, w = gray.shape
    cy, cx = h//2, w//2 # here is for the inequality equation in hw04, for compute the D_r
    r = int(0.1 * min(h, w)) # r = [alpha * min(h, w)] here, I set the alpha to 0.1
    y, x = np.ogrid[-cy:h-cy, -cx:w-cx] # we move the center of the circle to the [0, 0] point
    D_r = x*x + y*y <= r*r # here is the D_r, define the low-frequency disc
    total_energy = np.sum(fshift_abs)
    low_freq_energy = np.sum(fshift_abs[D_r])
    m['HFE'] = (total_energy - low_freq_energy) / (total_energy)
    
    # here is the mean local standard deviation, (3, 3) is the window size
    mean = cv2.blur(gray.astype(float), (3, 3))
    mean_sq = cv2.blur(gray.astype(float)**2, (3, 3))
    m['MLSD'] = np.sqrt(np.maximum(0, mean_sq - mean**2)).mean()
    
    # the last one is the GLCM contrast
    Q = 16 # we have to define Q grey levels
    # then I call the skimage library
    gray_q = (gray // (256 // Q)).astype(np.uint8)
    glcm = graycomatrix(gray_q, [1], [0], levels=Q, symmetric=True, normed=True)
    m['CON'] = graycoprops(glcm, 'contrast')[0, 0]
    
    return m


# here is the trainer class, which contains three models
class GenModelTrainer:
    def __init__(self, model_type, device='cuda', learning_rate):
        self.model_type = model_type
        self.device = device
        
        if model_type == "VAE":
            self.model = VAE().to(device)
            self.optimizer = torch.optim.Adam(self.model.parameters(), lr=learning_rate)
        elif model_type == "GAN":
            self.Generator = Generator().to(device)
            self.Discriminator = Discriminator().to(device)
            self.optimizerG = torch.optim.Adam(self.Generator.parameters(), lr=learning_rate)
            self.optimizerD = torch.optim.Adam(self.Discriminator.parameters(), lr=learning_rate)
            self.cost_function = nn.BCELoss() # for GAN, we use binary cross entropy loss for the discriminator and generator, because the discriminator is a binary classifier, and the generator's loss is also based on the discriminator's output
        elif model_type == "Diffusion":
            self.model = DiffusionNet().to(device)
            self.optimizer = torch.optim.Adam(self.model.parameters(), lr=learning_rate)

    def train_step(self, real_imgs, epoch, step):
        real_imgs = real_imgs.to(self.device)
        batch_size = real_imgs.size(0)

        if self.model_type == "VAE":
            recon_imgs, mu, log_var = self.model(real_imgs)
            recon_loss = F.mse_loss(recon_imgs, real_imgs, reduction='sum')
            # KL divergence loss
            kl_loss = -0.5 * torch.sum(1 + log_var - mu.pow(2) - log_var.exp())
            loss = (recon_loss + kl_loss) / batch_size
            
            self.optimizer.zero_grad()
            loss.backward()
            self.optimizer.step()
            return {"Epoch": epoch, "Step": step, "loss": loss.item()}

        elif self.model_type == "GAN":
            # update the discriminator by using max(log(D(x)) + log(1 - D(G(z))))
            # first we need to train the discriminator with real images, this is because we want the discriminator know what real images look like, then we train the discriminator with fake images, and we add the loss together, because we want the discriminator give a very clear line between real and fake images, the we give the discriminator some sort of image that is generated by the generator, it will work.
            self.optimizerD.zero_grad()
            label_real = torch.full((batch_size,), 1.0, device=self.device)
            label_fake = torch.full((batch_size,), 0.0, device=self.device)
            
            output_real = self.Discriminator(real_imgs).view(-1)
            lossD_real = self.cost_function(output_real, label_real)
            
            noise = torch.randn(batch_size, 100, 1, 1, device=self.device)
            fake_imgs = self.Generator(noise)
            output_fake = self.Discriminator(fake_imgs.detach()).view(-1)
            lossD_fake = self.cost_function(output_fake, label_fake)
            
            lossD = lossD_real + lossD_fake
            lossD.backward()
            self.optimizerD.step()

            # then we train the generator, we use the fake images to compute the output, and force this output to be the real one, so here we use label_real, because we want to fool the discriminator, we want the discriminator think the fake images are real, so we use label_real as the target for the generator's loss
            self.optimizerG.zero_grad()
            output = self.Discriminator(fake_imgs).view(-1)
            lossG = self.cost_function(output, label_real)
            lossG.backward()
            self.optimizerG.step()
            return {"Epoch": epoch, "Step": step, "lossG": lossG.item(), "lossD": lossD.item()}

        elif self.model_type == "Diffusion":
            # randomly sample a time step t for each image in the batch and the noise
            t = torch.randint(0, 1000, (batch_size,), device=self.device)
            noise = torch.randn_like(real_imgs)
            # add the noise
            x_noisy = real_imgs + noise 
            
            predicted_noise = self.model(x_noisy, t)
            loss = F.mse_loss(predicted_noise, noise)
            
            self.optimizer.zero_grad()
            loss.backward()
            self.optimizer.step()
            return {"Epoch": epoch, "Step": step, "loss": loss.item()}